[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
HCIDatasets = "1893dc6a-5236-4cb8-aa54-62ea411c10cd"
LossFunctions = "30fc2ffe-d236-52d8-8643-a9d8f7c094a7"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
PSFModels = "9ba017d1-7760-46cd-84a3-1e79e9ae9ddc"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"

[compat]
Documenter = "0.25"
HCIDatasets = "0.2"
LossFunctions = "0.5, 0.6"
Optim = "1"
Plots = "1"
